services:
  ticker-producer:
    image: node:20
    container_name: oflow-ticker
    restart: on-failure
    environment:
      SERVER_PROFILE: TickerProducer
      SERVER_NODE_ID: docker-ticker
    ports:
      - 6500:6500
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main

  publisher:
    image: node:20
    container_name: oflow-publisher
    restart: on-failure
    environment:
      SERVER_PROFILE: DataPublisher
      SERVER_NODE_ID: docker-publisher
    ports:
      - 7000:7000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main

  data-server:
    image: node:20
    container_name: oflow-server
    # restart: on-failure
    environment:
      SERVER_PROFILE: OflowServer
      SERVER_NODE_ID: docker-server
    ports:
      - 15000:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main
