services:
  redis:
    image: redis/redis-stack
    container_name: ops-redis
    volumes:
      - redis-data:/data
    ports:
      - "26379:6379"
      - "28001:8001"
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD:-3ZYRTpxcvUnZXipv9uekMJ}

volumes:
  redis-data: { }
