CREATE INDEX t_kline_1s_symbol_time_index ON tm.t_kline_1s (symbol, time);
CREATE INDEX t_kline_1s_ex_symbol_time_index ON tm.t_kline_1s (ex, symbol, time);
CREATE INDEX t_fp_1s_p1_symbol_time_index ON tm.t_fp_1s_p1 (symbol, time);
CREATE INDEX t_fp_1s_p1_ex_symbol_time_index ON tm.t_fp_1s_p1 (ex, symbol, time);
CREATE INDEX t_kline_5s_symbol_time_index ON tm.t_kline_5s (symbol, time);
CREATE INDEX t_kline_5s_ex_symbol_time_index ON tm.t_kline_5s (ex, symbol, time);
CREATE INDEX t_kline_30s_symbol_time_index ON tm.t_kline_30s (symbol, time);
CREATE INDEX t_kline_30s_ex_symbol_time_index ON tm.t_kline_30s (ex, symbol, time);
CREATE INDEX t_kline_1m_symbol_time_index ON tm.t_kline_1m (symbol, time);
CREATE INDEX t_kline_1m_ex_symbol_time_index ON tm.t_kline_1m (ex, symbol, time);
CREATE INDEX t_kline_5m_symbol_time_index ON tm.t_kline_5m (symbol, time);
CREATE INDEX t_kline_5m_ex_symbol_time_index ON tm.t_kline_5m (ex, symbol, time);
CREATE INDEX t_kline_15m_symbol_time_index ON tm.t_kline_15m (symbol, time);
CREATE INDEX t_kline_15m_ex_symbol_time_index ON tm.t_kline_15m (ex, symbol, time);
CREATE INDEX t_kline_1h_symbol_time_index ON tm.t_kline_1h (symbol, time);
CREATE INDEX t_kline_1h_ex_symbol_time_index ON tm.t_kline_1h (ex, symbol, time);
CREATE INDEX t_kline_4h_symbol_time_index ON tm.t_kline_4h (symbol, time);
CREATE INDEX t_kline_4h_ex_symbol_time_index ON tm.t_kline_4h (ex, symbol, time);
CREATE INDEX t_kline_1d_symbol_time_index ON tm.t_kline_1d (symbol, time);
CREATE INDEX t_kline_1d_ex_symbol_time_index ON tm.t_kline_1d (ex, symbol, time);
CREATE INDEX t_fp_1s_p2_symbol_time_index ON tm.t_fp_1s_p2 (symbol, time);
CREATE INDEX t_fp_1s_p2_ex_symbol_time_index ON tm.t_fp_1s_p2 (ex, symbol, time);
CREATE INDEX t_fp_1s_p4_symbol_time_index ON tm.t_fp_1s_p4 (symbol, time);
CREATE INDEX t_fp_1s_p4_ex_symbol_time_index ON tm.t_fp_1s_p4 (ex, symbol, time);
CREATE INDEX t_fp_1s_p8_symbol_time_index ON tm.t_fp_1s_p8 (symbol, time);
CREATE INDEX t_fp_1s_p8_ex_symbol_time_index ON tm.t_fp_1s_p8 (ex, symbol, time);
CREATE INDEX t_fp_5s_p1_symbol_time_index ON tm.t_fp_5s_p1 (symbol, time);
CREATE INDEX t_fp_5s_p1_ex_symbol_time_index ON tm.t_fp_5s_p1 (ex, symbol, time);
CREATE INDEX t_fp_5s_p2_symbol_time_index ON tm.t_fp_5s_p2 (symbol, time);
CREATE INDEX t_fp_5s_p2_ex_symbol_time_index ON tm.t_fp_5s_p2 (ex, symbol, time);
CREATE INDEX t_fp_5s_p4_symbol_time_index ON tm.t_fp_5s_p4 (symbol, time);
CREATE INDEX t_fp_5s_p4_ex_symbol_time_index ON tm.t_fp_5s_p4 (ex, symbol, time);
CREATE INDEX t_fp_5s_p8_symbol_time_index ON tm.t_fp_5s_p8 (symbol, time);
CREATE INDEX t_fp_5s_p8_ex_symbol_time_index ON tm.t_fp_5s_p8 (ex, symbol, time);
CREATE INDEX t_fp_5s_p16_symbol_time_index ON tm.t_fp_5s_p16 (symbol, time);
CREATE INDEX t_fp_5s_p16_ex_symbol_time_index ON tm.t_fp_5s_p16 (ex, symbol, time);
CREATE INDEX t_fp_30s_p1_symbol_time_index ON tm.t_fp_30s_p1 (symbol, time);
CREATE INDEX t_fp_30s_p1_ex_symbol_time_index ON tm.t_fp_30s_p1 (ex, symbol, time);
CREATE INDEX t_fp_30s_p2_symbol_time_index ON tm.t_fp_30s_p2 (symbol, time);
CREATE INDEX t_fp_30s_p2_ex_symbol_time_index ON tm.t_fp_30s_p2 (ex, symbol, time);
CREATE INDEX t_fp_30s_p4_symbol_time_index ON tm.t_fp_30s_p4 (symbol, time);
CREATE INDEX t_fp_30s_p4_ex_symbol_time_index ON tm.t_fp_30s_p4 (ex, symbol, time);
CREATE INDEX t_fp_30s_p8_symbol_time_index ON tm.t_fp_30s_p8 (symbol, time);
CREATE INDEX t_fp_30s_p8_ex_symbol_time_index ON tm.t_fp_30s_p8 (ex, symbol, time);
CREATE INDEX t_fp_30s_p16_symbol_time_index ON tm.t_fp_30s_p16 (symbol, time);
CREATE INDEX t_fp_30s_p16_ex_symbol_time_index ON tm.t_fp_30s_p16 (ex, symbol, time);
CREATE INDEX t_fp_30s_p32_symbol_time_index ON tm.t_fp_30s_p32 (symbol, time);
CREATE INDEX t_fp_30s_p32_ex_symbol_time_index ON tm.t_fp_30s_p32 (ex, symbol, time);
CREATE INDEX t_fp_1m_p1_symbol_time_index ON tm.t_fp_1m_p1 (symbol, time);
CREATE INDEX t_fp_1m_p1_ex_symbol_time_index ON tm.t_fp_1m_p1 (ex, symbol, time);
CREATE INDEX t_fp_1m_p2_symbol_time_index ON tm.t_fp_1m_p2 (symbol, time);
CREATE INDEX t_fp_1m_p2_ex_symbol_time_index ON tm.t_fp_1m_p2 (ex, symbol, time);
CREATE INDEX t_fp_1m_p4_symbol_time_index ON tm.t_fp_1m_p4 (symbol, time);
CREATE INDEX t_fp_1m_p4_ex_symbol_time_index ON tm.t_fp_1m_p4 (ex, symbol, time);
CREATE INDEX t_fp_1m_p8_symbol_time_index ON tm.t_fp_1m_p8 (symbol, time);
CREATE INDEX t_fp_1m_p8_ex_symbol_time_index ON tm.t_fp_1m_p8 (ex, symbol, time);
CREATE INDEX t_fp_1m_p16_symbol_time_index ON tm.t_fp_1m_p16 (symbol, time);
CREATE INDEX t_fp_1m_p16_ex_symbol_time_index ON tm.t_fp_1m_p16 (ex, symbol, time);
CREATE INDEX t_fp_1m_p32_symbol_time_index ON tm.t_fp_1m_p32 (symbol, time);
CREATE INDEX t_fp_1m_p32_ex_symbol_time_index ON tm.t_fp_1m_p32 (ex, symbol, time);
CREATE INDEX t_fp_1m_p64_symbol_time_index ON tm.t_fp_1m_p64 (symbol, time);
CREATE INDEX t_fp_1m_p64_ex_symbol_time_index ON tm.t_fp_1m_p64 (ex, symbol, time);
CREATE INDEX t_fp_5m_p1_symbol_time_index ON tm.t_fp_5m_p1 (symbol, time);
CREATE INDEX t_fp_5m_p1_ex_symbol_time_index ON tm.t_fp_5m_p1 (ex, symbol, time);
CREATE INDEX t_fp_5m_p2_symbol_time_index ON tm.t_fp_5m_p2 (symbol, time);
CREATE INDEX t_fp_5m_p2_ex_symbol_time_index ON tm.t_fp_5m_p2 (ex, symbol, time);
CREATE INDEX t_fp_5m_p4_symbol_time_index ON tm.t_fp_5m_p4 (symbol, time);
CREATE INDEX t_fp_5m_p4_ex_symbol_time_index ON tm.t_fp_5m_p4 (ex, symbol, time);
CREATE INDEX t_fp_5m_p8_symbol_time_index ON tm.t_fp_5m_p8 (symbol, time);
CREATE INDEX t_fp_5m_p8_ex_symbol_time_index ON tm.t_fp_5m_p8 (ex, symbol, time);
CREATE INDEX t_fp_5m_p16_symbol_time_index ON tm.t_fp_5m_p16 (symbol, time);
CREATE INDEX t_fp_5m_p16_ex_symbol_time_index ON tm.t_fp_5m_p16 (ex, symbol, time);
CREATE INDEX t_fp_5m_p32_symbol_time_index ON tm.t_fp_5m_p32 (symbol, time);
CREATE INDEX t_fp_5m_p32_ex_symbol_time_index ON tm.t_fp_5m_p32 (ex, symbol, time);
CREATE INDEX t_fp_5m_p64_symbol_time_index ON tm.t_fp_5m_p64 (symbol, time);
CREATE INDEX t_fp_5m_p64_ex_symbol_time_index ON tm.t_fp_5m_p64 (ex, symbol, time);
CREATE INDEX t_fp_5m_p128_symbol_time_index ON tm.t_fp_5m_p128 (symbol, time);
CREATE INDEX t_fp_5m_p128_ex_symbol_time_index ON tm.t_fp_5m_p128 (ex, symbol, time);
CREATE INDEX t_fp_15m_p1_symbol_time_index ON tm.t_fp_15m_p1 (symbol, time);
CREATE INDEX t_fp_15m_p1_ex_symbol_time_index ON tm.t_fp_15m_p1 (ex, symbol, time);
CREATE INDEX t_fp_15m_p2_symbol_time_index ON tm.t_fp_15m_p2 (symbol, time);
CREATE INDEX t_fp_15m_p2_ex_symbol_time_index ON tm.t_fp_15m_p2 (ex, symbol, time);
CREATE INDEX t_fp_15m_p4_symbol_time_index ON tm.t_fp_15m_p4 (symbol, time);
CREATE INDEX t_fp_15m_p4_ex_symbol_time_index ON tm.t_fp_15m_p4 (ex, symbol, time);
CREATE INDEX t_fp_15m_p8_symbol_time_index ON tm.t_fp_15m_p8 (symbol, time);
CREATE INDEX t_fp_15m_p8_ex_symbol_time_index ON tm.t_fp_15m_p8 (ex, symbol, time);
CREATE INDEX t_fp_15m_p16_symbol_time_index ON tm.t_fp_15m_p16 (symbol, time);
CREATE INDEX t_fp_15m_p16_ex_symbol_time_index ON tm.t_fp_15m_p16 (ex, symbol, time);
CREATE INDEX t_fp_15m_p32_symbol_time_index ON tm.t_fp_15m_p32 (symbol, time);
CREATE INDEX t_fp_15m_p32_ex_symbol_time_index ON tm.t_fp_15m_p32 (ex, symbol, time);
CREATE INDEX t_fp_15m_p64_symbol_time_index ON tm.t_fp_15m_p64 (symbol, time);
CREATE INDEX t_fp_15m_p64_ex_symbol_time_index ON tm.t_fp_15m_p64 (ex, symbol, time);
CREATE INDEX t_fp_15m_p128_symbol_time_index ON tm.t_fp_15m_p128 (symbol, time);
CREATE INDEX t_fp_15m_p128_ex_symbol_time_index ON tm.t_fp_15m_p128 (ex, symbol, time);
CREATE INDEX t_fp_15m_p256_symbol_time_index ON tm.t_fp_15m_p256 (symbol, time);
CREATE INDEX t_fp_15m_p256_ex_symbol_time_index ON tm.t_fp_15m_p256 (ex, symbol, time);
CREATE INDEX t_fp_1h_p1_symbol_time_index ON tm.t_fp_1h_p1 (symbol, time);
CREATE INDEX t_fp_1h_p1_ex_symbol_time_index ON tm.t_fp_1h_p1 (ex, symbol, time);
CREATE INDEX t_fp_1h_p4_symbol_time_index ON tm.t_fp_1h_p4 (symbol, time);
CREATE INDEX t_fp_1h_p4_ex_symbol_time_index ON tm.t_fp_1h_p4 (ex, symbol, time);
CREATE INDEX t_fp_1h_p8_symbol_time_index ON tm.t_fp_1h_p8 (symbol, time);
CREATE INDEX t_fp_1h_p8_ex_symbol_time_index ON tm.t_fp_1h_p8 (ex, symbol, time);
CREATE INDEX t_fp_1h_p16_symbol_time_index ON tm.t_fp_1h_p16 (symbol, time);
CREATE INDEX t_fp_1h_p16_ex_symbol_time_index ON tm.t_fp_1h_p16 (ex, symbol, time);
CREATE INDEX t_fp_1h_p32_symbol_time_index ON tm.t_fp_1h_p32 (symbol, time);
CREATE INDEX t_fp_1h_p32_ex_symbol_time_index ON tm.t_fp_1h_p32 (ex, symbol, time);
CREATE INDEX t_fp_1h_p64_symbol_time_index ON tm.t_fp_1h_p64 (symbol, time);
CREATE INDEX t_fp_1h_p64_ex_symbol_time_index ON tm.t_fp_1h_p64 (ex, symbol, time);
CREATE INDEX t_fp_1h_p128_symbol_time_index ON tm.t_fp_1h_p128 (symbol, time);
CREATE INDEX t_fp_1h_p128_ex_symbol_time_index ON tm.t_fp_1h_p128 (ex, symbol, time);
CREATE INDEX t_fp_1h_p256_symbol_time_index ON tm.t_fp_1h_p256 (symbol, time);
CREATE INDEX t_fp_1h_p256_ex_symbol_time_index ON tm.t_fp_1h_p256 (ex, symbol, time);
CREATE INDEX t_fp_1h_p512_symbol_time_index ON tm.t_fp_1h_p512 (symbol, time);
CREATE INDEX t_fp_1h_p512_ex_symbol_time_index ON tm.t_fp_1h_p512 (ex, symbol, time);
CREATE INDEX t_fp_4h_p1_symbol_time_index ON tm.t_fp_4h_p1 (symbol, time);
CREATE INDEX t_fp_4h_p1_ex_symbol_time_index ON tm.t_fp_4h_p1 (ex, symbol, time);
CREATE INDEX t_fp_4h_p16_symbol_time_index ON tm.t_fp_4h_p16 (symbol, time);
CREATE INDEX t_fp_4h_p16_ex_symbol_time_index ON tm.t_fp_4h_p16 (ex, symbol, time);
CREATE INDEX t_fp_4h_p32_symbol_time_index ON tm.t_fp_4h_p32 (symbol, time);
CREATE INDEX t_fp_4h_p32_ex_symbol_time_index ON tm.t_fp_4h_p32 (ex, symbol, time);
CREATE INDEX t_fp_4h_p64_symbol_time_index ON tm.t_fp_4h_p64 (symbol, time);
CREATE INDEX t_fp_4h_p64_ex_symbol_time_index ON tm.t_fp_4h_p64 (ex, symbol, time);
CREATE INDEX t_fp_4h_p128_symbol_time_index ON tm.t_fp_4h_p128 (symbol, time);
CREATE INDEX t_fp_4h_p128_ex_symbol_time_index ON tm.t_fp_4h_p128 (ex, symbol, time);
CREATE INDEX t_fp_4h_p256_symbol_time_index ON tm.t_fp_4h_p256 (symbol, time);
CREATE INDEX t_fp_4h_p256_ex_symbol_time_index ON tm.t_fp_4h_p256 (ex, symbol, time);
CREATE INDEX t_fp_4h_p512_symbol_time_index ON tm.t_fp_4h_p512 (symbol, time);
CREATE INDEX t_fp_4h_p512_ex_symbol_time_index ON tm.t_fp_4h_p512 (ex, symbol, time);
CREATE INDEX t_fp_4h_p1024_symbol_time_index ON tm.t_fp_4h_p1024 (symbol, time);
CREATE INDEX t_fp_4h_p1024_ex_symbol_time_index ON tm.t_fp_4h_p1024 (ex, symbol, time);
CREATE INDEX t_fp_1d_p1_symbol_time_index ON tm.t_fp_1d_p1 (symbol, time);
CREATE INDEX t_fp_1d_p1_ex_symbol_time_index ON tm.t_fp_1d_p1 (ex, symbol, time);
CREATE INDEX t_fp_1d_p32_symbol_time_index ON tm.t_fp_1d_p32 (symbol, time);
CREATE INDEX t_fp_1d_p32_ex_symbol_time_index ON tm.t_fp_1d_p32 (ex, symbol, time);
CREATE INDEX t_fp_1d_p64_symbol_time_index ON tm.t_fp_1d_p64 (symbol, time);
CREATE INDEX t_fp_1d_p64_ex_symbol_time_index ON tm.t_fp_1d_p64 (ex, symbol, time);
CREATE INDEX t_fp_1d_p128_symbol_time_index ON tm.t_fp_1d_p128 (symbol, time);
CREATE INDEX t_fp_1d_p128_ex_symbol_time_index ON tm.t_fp_1d_p128 (ex, symbol, time);
CREATE INDEX t_fp_1d_p256_symbol_time_index ON tm.t_fp_1d_p256 (symbol, time);
CREATE INDEX t_fp_1d_p256_ex_symbol_time_index ON tm.t_fp_1d_p256 (ex, symbol, time);
CREATE INDEX t_fp_1d_p512_symbol_time_index ON tm.t_fp_1d_p512 (symbol, time);
CREATE INDEX t_fp_1d_p512_ex_symbol_time_index ON tm.t_fp_1d_p512 (ex, symbol, time);
CREATE INDEX t_fp_1d_p1024_symbol_time_index ON tm.t_fp_1d_p1024 (symbol, time);
CREATE INDEX t_fp_1d_p1024_ex_symbol_time_index ON tm.t_fp_1d_p1024 (ex, symbol, time);
CREATE INDEX t_fp_1d_p2048_symbol_time_index ON tm.t_fp_1d_p2048 (symbol, time);
CREATE INDEX t_fp_1d_p2048_ex_symbol_time_index ON tm.t_fp_1d_p2048 (ex, symbol, time);