### kline
GET http://{{server}}/opsd/data/kline/okx/BTC-USDT/1h?timeFrom=1673260628000
Accept: application/json


### footprint
GET http://{{server}}/opsd/data/footprint/binance/BTC-PERP%2FBTC/1m?timeFrom=1674050160000&prl=1
Accept: application/json


### ticker
GET http://{{server}}/opsd/data/ticker/okx/BTC-USDT?timeFrom=1673260628000
Accept: application/json


### kline agg
GET http://{{server}}/opsd/data/kline/okx/BTC-USDT/1.m?timeFrom=1673260628000
Accept: application/json


### ticker agg
GET http://{{server}}/opsd/data/ticker/okx/BTC-USDT?timeFrom=1673260628000
Accept: application/json

