### create daily task
POST http://{{server}}/data-loader/create-tasks-for-each-day
Content-Type: application/json

{
  "exs": [
    "okx"
  ],
  "symbols": [
    "DOGE/USDT"
  ],
  "intervals": [
    "1d",
    "4h",
    "1h",
    "15m",
    "5m",
    "1m"
  ],
  "startDate": "2024-10-01",
  "endDate": "2024-10-31",
  "summitJobs": true,
  "skipExist": true
}


### create monthly task
POST http://{{server}}/data-loader/create-tasks-for-each-month
Content-Type: application/json

{
  "exs": [
    "okx"
  ],
  "symbols": [
    "BTC/USDT"
  ],
  "intervals": [
    "1d"
  ],
  "startDate": "2018-01",
  "endDate": "2024-11",
  "summitJobs": true,
  "skipExist": true
}

