
### all
GET http://{{server}}/ops/bt-strategies


### orders
GET http://{{server}}/ops/bt-strategies/35/orders
Accept: application/json


### job - summit ('summit' | 'remove' | 'stop' | 'retry' | 'clearLogs')
POST http://{{server}}/ops/bt-strategies/35/job/summit
Accept: application/json
