
### all
GET http://{{server}}/ops/strategies


### paper trade
GET http://{{server}}/ops/strategies?type=paper
Accept: application/json


### real trade
GET http://{{server}}/ops/strategies?type=real
Accept: application/json


### orders
GET http://{{server}}/ops/strategies/35/orders
Accept: application/json


### deals
GET http://{{server}}/ops/strategies/35/deals
Accept: application/json


### job - summit ('summit' | 'remove' | 'stop' | 'retry' | 'clearLogs')
POST http://{{server}}/ops/strategies/35/job/summit
Accept: application/json
