services:
  admin:
    image: node:20
    container_name: ops-admin
    # restart: on-failure
    environment:
      TZ: UTC
      SERVER_PROFILE: Admin
      SERVER_NODE_ID: server
    ports:
      - 5000:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main

  worker-st:
    image: node:20
    container_name: ops-worker-st
    restart: on-failure
    environment:
      TZ: UTC
      SERVER_PROFILE: StrategyWorker
      SERVER_NODE_ID: worker-st
    #    ports:
    #      - 7000:7000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main

  worker-pt:
    image: node:20
    container_name: ops-worker-pt
    restart: on-failure
    environment:
      TZ: UTC
      SERVER_PROFILE: PaperTradeWorker
      SERVER_NODE_ID: worker-pt
    #    ports:
    #      - 7000:7000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main

  worker-bt:
    image: node:20
    container_name: ops-worker-bt
    restart: on-failure
    environment:
      TZ: UTC
      SERVER_PROFILE: BacktestWorker
      SERVER_NODE_ID: worker-bt
    #    ports:
    #      - 7000:7000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main

  worker-dl:
    image: node:20
    container_name: ops-worker-dl
    restart: on-failure
    environment:
      TZ: UTC
      SERVER_PROFILE: ExDataLoaderWorker
      SERVER_NODE_ID: worker-dl
    #    ports:
    #      - 7000:7000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main

