services:
  worker:
    image: node:20
    container_name: ops-worker
    restart: on-failure
    environment:
      SERVER_PROFILE: Worker
      SERVER_NODE_ID: worker
    ports:
      - 7000:7000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main

  admin:
    image: node:20
    container_name: ops-admin
    # restart: on-failure
    environment:
      SERVER_PROFILE: Admin
      SERVER_NODE_ID: server
    ports:
      - 15000:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main
