services:
  kafka:
    image: docker.io/bitnami/kafka:3.8
    user: root
    container_name: ops-kafka
    ports:
      - "9092:9092"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - kafka-data:/bitnami
    #      - ./conf/kafka:/opt/bitnami/kafka/config
    #      - ../logs/kafka:/opt/bitnami/kafka/logs
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181/kafka
      #      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST}:9092
      - KAFKA_CFG_BROKER_ID=10
      - KAFKA_HEAP_OPTS=-Xmx4g -Xms2g

  zookeeper:
    image: zookeeper:3.9
    container_name: ops-zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zk-data:/data
      - zk-datalog:/datalog
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes


volumes:
  kafka-data: { }
  zk-data: { }
  zk-datalog: { }
