
### exWsInstances
GRAPHQL http://{{oflowServer}}/graphql

query {
  exWsInstances(input: {
    exchange: okx,
  })
}


### exWsStatus
GRAPHQL http://{{oflowServer}}/graphql

query {
  exWsStatus(input: {
    exchange: okx,
    # wsInstance: {
    #   # ids: "public-ws:instrument"
    #   # category: "order-book"
    #   forSymbol: "DOT-PERP"
    # }
    type: subjects
  })
}


### exWsRunningSymbols
GRAPHQL http://{{oflowServer}}/graphql

query {
  exWsRunningSymbols(input: {
    exchange: okx,
    # wsInstance: {
    #   instanceIndex: 2
    #   # forSymbol: "ETH/USD"
    # }
    channel: "tickers"
  })
}


### exWsObserveStatus
GRAPHQL http://{{oflowServer}}/graphql

subscription {
  exWsObserveStatus (input: {
    exchange: okx,
    wsInstance: {
      ids: "public-ws:1"
    }
    type: subjects
    interval: 3000
    maxSeconds: 60
  })
}


### exWsObserveChannel
GRAPHQL http://{{oflowServer}}/graphql

subscription {
  exWsObserveChannel (input: {
    exchange: okx,
    # wsInstance: {
    #   # ids: "public-ws:3"
    #   forSymbol: "BTC-USDT"
    # }
    channel: "tickers"
    minInterval: 1000
    maxTake: 10
    # filter: {
    #   path: "symbol"
    #   value: "BTC-USDT"
    # }
  })
}

