services:
  exws:
    image: node:20
    container_name: opsd-exws
    restart: on-failure
    environment:
      SERVER_PROFILE: Exws
      SERVER_NODE_ID: docker-exws
    ports:
      - 6500:6500
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main

  worker:
    image: node:20
    container_name: opsd-worker
    restart: on-failure
    environment:
      SERVER_PROFILE: Worker
      SERVER_NODE_ID: docker-worker
    ports:
      - 7000:7000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main

  data-server:
    image: node:20
    container_name: opsd-server
    # restart: on-failure
    environment:
      SERVER_PROFILE: DataServer
      SERVER_NODE_ID: docker-server
    ports:
      - 15000:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main
