### trades
// It is possible to specify client messages in request body. Use '===' to separate messages.
// Add '=== wait-for-server' above a message to send it after a server response is received.
// To wait for N responses, add '=== wait-for-server' N times.
WEBSOCKET wss://wsaws.okx.com:8443/ws/v5/public
Content-Type: application/json // We use it for highlighting

{
  "op": "subscribe",
  "args": [
    {
      "channel": "trades",
      "instId": "BTC-USDT"
    }
  ]
}

### history-trades
GET https://www.okx.com/api/v5/market/history-trades?instId=BTC-USDT
Accept: application/json
