services:
  server:
    image: node:20
    container_name: ops-all
    restart: on-failure
    environment:
      TZ: UTC
      SERVER_PROFILE: RunAll
      SERVER_NODE_ID: server
    ports:
      - 5000:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../..:/app
    working_dir: /app
    command:
      - dist/main
